version: '1'
services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - client

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /data/db